plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace 'com.example.readerhub'
    compileSdk 36

    defaultConfig {
        applicationId "com.example.readerhub"
        minSdk 23
        targetSdk 36
        versionCode 1
        versionName "1.0"

        // Читаем URL из local.properties или используем дефолтный
        Properties properties = new Properties()
        if (rootProject.file("local.properties").exists()) {
            properties.load(rootProject.file("local.properties").newDataInputStream())
        }

        buildConfigField "String", "API_BASE_URL",
                properties.getProperty("api.base.url", '""')

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    buildFeatures {
        buildConfig = true
        viewBinding true
    }
    viewBinding {
        enabled true
    }
}

dependencies {

    implementation libs.appcompat.v171
    implementation libs.material.v1110
    implementation libs.constraintlayout.v221
    implementation libs.cardview
    implementation libs.recyclerview

    // Room Database
    implementation libs.room.runtime.v261
    annotationProcessor libs.room.compiler.v261

    // Retrofit & OkHttp
    implementation libs.retrofit.v290
    implementation libs.converter.gson.v290
    implementation libs.okhttp
    implementation libs.logging.interceptor

    // Jsoup for HTML parsing
    implementation libs.jsoup

    // EPUB Reader
    implementation 'com.folioreader:folioreader:0.5.4'

    // PDF Viewer
    implementation libs.android.pdf.viewer

    // Glide for image loading
    implementation 'com.github.bumptech.glide:glide:5.0.5'
    annotationProcessor libs.compiler

    // Testing
    testImplementation libs.junit
    androidTestImplementation libs.junit.v130
    androidTestImplementation libs.espresso.core.v370
    annotationProcessor libs.room.compiler
}